server:
  port: 4004

### REST CLIENT -> http:localhost:4004/[predicates] such as http:localhost:4004/api/patients
### API GATEWAY -> http://patient-service:8080/patients

spring:
  cloud:
    gateway:
      routes:
        - id: patient-service-route
          uri: http://patient-service:8080
          predicates:
            - Path=/api/patients/**
          filters:
            - StripPrefix=1
        - id: api-docs-patient-route
          uri: http://patient-service:8080
          predicates:
            - Path=/api-docs/patients
          filters:
            - RewritePath=/api-docs/patients,/v3/api-docs


logging:
  level:
    org.springframework.cloud.gateway: DEBUG
